version: '3.3'

services: 
  db:
    container_name: database
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: "orbeem"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

  api: 
    container_name: api
    image: ec2-app
    depends_on: 
      - db
    build: 
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "4000:4000"
    
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"